# 应用名称
spring.application.name: HomeworkSystem
# mysql 8  驱动不同com.mysql.cj.jdbc.Driver、需要增加时区的配置  serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: "0926"
spring.datasource.url: jdbc:mysql://47.101.213.150:3306/homeworkSystem?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
# 配置日志
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring.main:
  allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


spring:
  redis:
    host: 47.101.213.150
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
        #最小空闲
  rabbitmq:
    host: 47.101.213.150
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  minio:
    url: http://47.101.213.150:9000
    endpoint: http://47.101.213.150:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: homework